version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    target-branch: preview
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /pulumi-component/provider
    target-branch: preview
    schedule:
      interval: daily
