# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import errno
from setuptools import setup, find_packages
from setuptools.command.install import install
from subprocess import check_call


VERSION = "0.0.0"
def readme():
    try:
        with open('README.md', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        return "hcloud-kube-hetzner Pulumi Package - Development Version"


setup(name='pulumi_hcloud_kube_hetzner',
      python_requires='>=3.7',
      version=VERSION,
      long_description=readme(),
      long_description_content_type='text/markdown',
      keywords='pulumi kubernetes kind/component category/infrastructure',
      packages=find_packages(),
      package_data={
          'pulumi_hcloud_kube_hetzner': [
              'py.typed',
              'pulumi-plugin.json',
          ]
      },
      install_requires=[
          'parver>=0.2.1',
          'pulumi>=3.0.0,<4.0.0',
          'pulumi-kubernetes>=4.0.0,<5.0.0',
          'semver>=2.8.1'
      ],
      zip_safe=False)
