// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace cluster {
    export interface Servers {
        internalIP?: string;
        ip?: string;
        name?: string;
        user?: string;
    }

}
