name: prepare-pulumi
description: "Prepare credentials and pulumi stack for github CI"
inputs:
  google-credentials:
    required: true
    description: "credentials for GCP pulumi backend"
  create-stack:
    required: true
    description: "create stack or not"
  disable-go-deps:
    required: false
    description: "disable go cache"
  template:
    required: false
    type: string
    description: 'source of pulumi template'
    default: go/library

runs:
  using: "composite"
  steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ inputs.google-credentials }}'
    - name: Setup Go ✨
      uses: actions/setup-go@v4
      with:
        cache: false
        go-version-file: go.mod
    - name: Wait for builds
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ github.ref }}
        check-name: "Build and save component binary for sha ${{ github.sha }}"
        wait-interval: 10
      if: ${{ inputs.template != 'go/library' }}
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v3
      with:
        workflow: all-build-component.yaml
        workflow_conclusion: ""
      if: ${{ inputs.template != 'go/library' }}
    - name: Add component to PATH directory
      run: mv -v pulumi-component-* /usr/local/bin/pulumi-resource-hcloud-kube-hetzner
      shell: bash
      if: ${{ inputs.template != 'go/library' }}
    - name: Create a temporary Pulumi project
      run: make test-go-project
      env:
        TEMPLATE: ${{ inputs.template }}
      shell: bash
      if: startsWith(inputs.template, 'go')
    - name: Downloading dependencies 📦
      if: ${{ ! inputs.disable-go-deps }} && startsWith(inputs.template, 'go')
      shell: bash
      run: go mod download
      working-directory: test-project
    - name: Install pulumi cli
      uses: pulumi/actions@v4
      with:
        pulumi-version: v3.99.0
    - name: Create a stack
      shell: bash
      if: ${{ inputs.create-stack == 'true'}}
      run: make pulumi-ci-prepare
      env:
        PULUMI_STACK_INIT_FLAGS: --secrets-provider=gcpkms://projects/spigell-infra/locations/global/keyRings/spigell-infra-keyring/cryptoKeys/spigell-infra-phkh-pulumi-key
        PULUMI_BACKEND: gs://spigell-infra-phkh-pulumi-states
        PULUMI_CONFIG_SOURCE: ../${{ env.PULUMI_CONFIG_SOURCE }}
      working-directory: test-project
    - name: Login to Pulumi
      shell: bash
      if: ${{ inputs.create-stack == 'false' }}
      run: make pulumi-login && make pulumi-select
      env:
        PULUMI_BACKEND: gs://spigell-infra-phkh-pulumi-states
      working-directory: test-project
