config:
  pulumi-hcloud-kube-hetzner:network:
    hetzner:
      enabled: true
      # It is highly recommended to set a cidr for the private network for at least /20
      cidr: 10.22.0.0/16
    wireguard:
      enabled: true
      firewall:
        hetzner:
          # Allow establish tunnel only from the ips for servers node only!
          allowed-ips:
            - '0.0.0.0/0'
  pulumi-hcloud-kube-hetzner:nodepools:
    agents:
      - id: big-nodes
        config:
          server:
            server-type: cpx31
        nodes:
        - id: k3s-big-agent01
      - id: ingress-node
        nodes:
        - id: k3s-ingress01
      - id: worker-nodes
        nodes:
        - id: k3s-agent01
    servers:
      - id: control-plane
        config:
          server:
            server-type: cpx21
        nodes:
        - id: k3s-server01
          leader: true
          server:
            location: fsn1
  pulumi-hcloud-kube-hetzner:defaults:
    agents:
      k3s:
        config:
          kubelet-arg:
            - node-status-update-frequency=20s
            - system-reserved=cpu=100m,memory=100Mi
    global:
      server:
        firewall:
          firewalld:
            enabled: false
          hetzner:
            enabled: true
            allow-icmp: true
            ssh:
              allow: true
      k3s:
        config:
          node-label:
            - k3os.io/upgrade=disabled
        version: v1.26.4+k3s1
    servers:
      k3s:
        config:
          cluster-cidr: 10.140.0.0/16
          cluster-dns: 10.141.0.10
          disable:
            - metrics-server
            - traefik
            - servicelb
          disable-cloud-controller: true
          kube-apiserver-arg:
            - default-not-ready-toleration-seconds=60
            - default-unreachable-toleration-seconds=60
          kube-controller-manager-arg:
            - node-monitor-grace-period=2m
          kubeet-arg:
            - node-status-update-frequency=20s
            - system-reserved=cpu=1,memory=1Gi
          node-taint:
            # This is default for control-plane nodes
            - CriticalAddonsOnly=true:NoExecute
            - node-role.kubernetes.io/control-plane:NoSchedule
          service-cidr: 10.141.0.0/16
