
Vagrant.configure("2") do |config|
  config.vm.box = 'bento/ubuntu-22.04'
  config.vm.guest = :linux

  config.ssh.forward_agent = true
  config.vm.network 'forwarded_port', guest: 22, host: 2222, disabled: false
  config.vm.synced_folder '.', '/vagrant', disabled: true
end
