name: The component building

on:
  push:
    tags-ignore:
      - '**'
    branches:
    - '**'

jobs:
  unit-tests:
    name: "Build and save component binary"
    runs-on: runs-on,runner=2cpu-linux-x64,run-id=${{ github.run_id }}
    steps:
      - uses: actions/checkout@v3
      - uses: runs-on/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go ✨
        uses: actions/setup-go@v4
        with:
          cache: false
          go-version-file: go.mod
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 6
      - name: Downloading dependencies 📦
        shell: bash
        run: go mod download
      - name: Make provider
        shell: bash
        run: make build_provider
        working-directory: pulumi-component
      - uses: actions/upload-artifact@v4
        with:
          name: pulumi-component-${{ steps.short-sha.outputs.sha }}
          path: pulumi-component/bin/pulumi-resource-hcloud-kube-hetzner
