name: Generate documentation
on: 
  - pull_request

jobs:
  generate:
    name: Update schema, SDK and documentation
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - uses: runs-on/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Setup Go ✨
      uses: actions/setup-go@v4
      with:
        cache: false
        go-version-file: go.mod
    - name: Generate docs
      run: go run ./cmd/generate-docs/main.go ./internal > docs/parameters.md
    - name: Generate SDK and schema
      run: make generate
      working-directory: pulumi-component
    - name: Build SDK
      run: make build_nodejs_sdk
      working-directory: pulumi-component
    - name: Check for changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add docs/parameters.md
        git commit -m "[auto] update docs" || echo 'Docs: no changes'
        git add pulumi-component/sdk
        git commit -m "[auto] update SDK" || echo 'SDK: no changes'
        git add pulumi-component/provider/cmd/pulumi-resource-hcloud-kube-hetzner/schema.json 
        git commit -m "[auto] update schema" || echo 'schema: no changes'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}

