name: The prebuilt binaries release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  component-release:
    name: "Release binaries"
    runs-on: ubuntu-latest
    if: github.event.base_ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: pulumi/pulumictl
      - name: Setup Go ✨
        uses: actions/setup-go@v4
        with:
          cache: false
          go-version-file: pulumi-component/provider/go.mod
      - name: Wait unit tests on the main branch
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: main
          check-name: "Run unit tests"
          repo-token: ${{ github.token }}
          wait-interval: 10
          allowed-conclusions: success,skipped
      - name: Generate schema for component
        run: make generate_schema
        working-directory: pulumi-component
      - name: Release required binaries
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
